import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const oldFont = localFont({
  variable: "--font-oldFont",
  src: [
    {
      path: "../public/assets/fonts/font.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

const circular = localFont({
  variable: "--font-circular",
  src: [
    {
      path: "../public/assets/fonts/circular.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

const ludovico = localFont({
  variable: "--font-ludovico",
  src: [
    {
      path: "../public/assets/fonts/ludovico.ttf",
    },
  ],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oldFont.variable} ${geistSans.variable} ${circular.variable} ${ludovico.variable} antialiased font-oldFont bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
